# The CI workflow tests Net-SSLeay against the following setups:
#
# - OS: Ubuntu 20.04
#
# - Perl: the latest patch release of every minor release since 5.8
#
# - libssl: the latest patch release of every minor release between:
#   - OpenSSL: 0.9.8 and 3.0
#   - LibreSSL: 2.2 and 3.5

name: CI

on:
  pull_request:
  push:
    branches:
      - master

env:
  PERL_MM_USE_DEFAULT: 1
  RELEASE_TESTING: 0

jobs:
  ubuntu-openssl:
    name: 'Ubuntu 20.04 (Perl ${{ matrix.perl }}, OpenSSL ${{ matrix.openssl }})'
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        perl:
          - '5.34'
          - '5.32'
          - '5.30'
          - '5.28'
          - '5.26'
          - '5.24'
          - '5.22'
          - '5.20'
          - '5.18'
          - '5.16'
          - '5.14'
          - '5.12'
          - '5.10'
          - '5.8'
        openssl:
          - '3.0.0'
          - '1.1.1l'
          - '1.1.0l'
          - '1.0.2u'
          - '1.0.1u'
          - '1.0.0t'
          - '0.9.8zh'
    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Install Perl ${{ matrix.perl }}
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}

      - name: 'Install OpenSSL ${{ matrix.openssl }}'
        run: |
          os="ubuntu-20.04"
          ver="openssl-${{ matrix.openssl }}"

          curl -L "https://github.com/p5-net-ssleay/ci-libssl/releases/download/$ver/$ver-$os.tar.xz" \
            | tar -C $HOME -Jx

      - name: Install dependencies
        run: cpanm --quiet --installdeps --notest .

      - name: Create makefile
        run: |
          LD_LIBRARY_PATH="$HOME/libssl/lib" \
          OPENSSL_PREFIX="$HOME/libssl" \
            perl Makefile.PL

      - name: Build
        run: |
          LD_LIBRARY_PATH="$HOME/libssl/lib" \
            make

      - name: Run test suite
        run: |
          LD_LIBRARY_PATH="$HOME/libssl/lib" \
            make test

  ubuntu-libressl:
    name: 'Ubuntu 20.04 (Perl ${{ matrix.perl }}, LibreSSL ${{ matrix.libressl }})'
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        perl:
          - '5.34'
          - '5.32'
          - '5.30'
          - '5.28'
          - '5.26'
          - '5.24'
          - '5.22'
          - '5.20'
          - '5.18'
          - '5.16'
          - '5.14'
          - '5.12'
          - '5.10'
          - '5.8'
        libressl:
          - '3.5.0'
          - '3.4.2'
          - '3.3.5'
          - '3.2.7'
          - '3.1.5'
          - '3.0.2'
          - '2.9.2'
          - '2.8.3'
          - '2.7.5'
          - '2.6.5'
          - '2.5.5'
          - '2.4.5'
          - '2.3.10'
          - '2.2.9'
    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Install Perl ${{ matrix.perl }}
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}

      - name: 'Install LibreSSL ${{ matrix.libressl }}'
        run: |
          os="ubuntu-20.04"
          ver="libressl-${{ matrix.libressl }}"

          curl -L "https://github.com/p5-net-ssleay/ci-libssl/releases/download/$ver/$ver-$os.tar.xz" \
            | tar -C $HOME -Jx

      - name: Install dependencies
        run: cpanm --quiet --installdeps --notest .

      - name: Create makefile
        run: |
          LD_LIBRARY_PATH="$HOME/libssl/lib" \
          OPENSSL_PREFIX="$HOME/libssl" \
            perl Makefile.PL

      - name: Build
        run: |
          LD_LIBRARY_PATH="$HOME/libssl/lib" \
            make

      - name: Run test suite
        run: |
          LD_LIBRARY_PATH="$HOME/libssl/lib" \
            make test
